[project]
name = "repl-nix-roboticsjobskimmer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "psycopg2-binary>=2.9.10",
    "streamlit>=1.40.1",
    "trafilatura>=1.12.2",
]
